version: 2

conda:
    environment: docs/environment.yml

build:
   image: latest

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: pip
      path: .
  system_packages: true

submodules:                                                                                                                          
    include: all
