version: 2

conda:
    environment: docs/environment.yml

build:
   image: latest

# This part is necessary otherwise the project is not built
python:
   version: 3.8
   install:
      - method: pip
      - requirements: docs/requirements.txt
        path: .
        
# By default readthedocs does not checkout git submodules
submodules:                                                                                                                          
    include: all
view raw
